#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: A Fishing Addiction

# Short bio or description (displayed in the header)
description: A blog about my fishing adventures

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: '' #https://avatars0.githubusercontent.com/u/533562

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  #email: dan@afishingaddiction.com
  facebook: AFishingAddiction
  flickr:
  github: AFishingAddiction/AFishingAddiction.github.io
  instagram: AFishingAddiction
  linkedin:
  pinterest:
  rss: 'feed.xml'
  twitter: AFishingAddict
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  #youtube: channel/UCUmAhj4E2UaaXntpG0dzWOQ
  #googleplus: 112420365100913161411 # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

comments:
  enabled: true
  form_action: "https://api.staticman.net/v2/entry/AFishingAddiction/AFishingAddiction.github.io/master/comments"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 'UA-16096735-3'

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://afishingaddiction.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

navlinks:
  - text: Home
    url: /
  - text: Maps
    url: '#'
    subnav:
    - text: Akron Area
      url: /akron-area-fishing-map/
    - text: Lake Erie
      url: /lake-erie-fishing-map/
    - text: AEP
      url: /aep-fishing-map/
  - text: Bio
    url: /authors/dan-schaefer/

include: ['_pages']

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
