#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: A Fishing Addiction

# Short bio or description (displayed in the header)
description: A blog about my bass fishing addiction

logo: /images/logo/A-Fishing-Addiction-logo.png

language: en-us
locale: en_US

# The author of the page if not specified on the post or page
author:
  name: Dan Schaefer
  picture: /images/dan-schaefer-profile-0-200x200.jpg
  twitter: AFishingAddict

static:
  image:
    path: 'images'

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: '' #https://avatars0.githubusercontent.com/u/533562

# Jekyll SEO
twitter:
  card: summary
  username: AFishingAddict
facebook:
  publisher: AFishingAddiction
  admins: danschaefer13
social:
  name: A Fishing Addiction
  links:
    - https://twitter.com/AFishingAddict
    - https://www.facebook.com/AFishingAddiction
    - https://www.instagram.com/AFishingAddiction
    - https://www.youtube.com/channel/UCUmAhj4E2UaaXntpG0dzWOQ
webmaster_verifications:
  google: _W7e1typcZprmr1vk0ZE833mlWAr-wD0-gGtbizBLY8

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: dan@afishingaddiction.com
  facebook: AFishingAddiction
  flickr:
  github: AFishingAddiction/AFishingAddiction.github.io
  instagram: AFishingAddiction
  linkedin:
  pinterest:
  rss: 'feed.xml'
  twitter: AFishingAddict
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCUmAhj4E2UaaXntpG0dzWOQ
  #googleplus: 112420365100913161411 # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

comments:
  enabled: true
  form_action: "https://api.staticman.net/v2/entry/AFishingAddiction/AFishingAddiction.github.io/master/comments"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 'G-Q8STFFHFDR'
google_tag_manager: 'GTM-WTWRNFW'

# Enter your Hotjar Id (e.g. 2079296)
# hotjar:
#   id: 2079296

cookiebot:
  id: 344a45ae-8133-4da1-bec0-11fdcf174a55

ads:
  adsense:
    client: 'ca-pub-3400524677609512'
    slots:
      responsive_horizontal: "3600433775"
      responsive_large_skyscraper: "3745020504"
      responsive_square: "1792438522"

affiliates:
  fishbrain:
    text_link: https://www.awin1.com/awclick.php?gid=388184&mid=19294&awinaffid=730047&linkid=2627727&clickref=

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://afishingaddiction.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

collections:
    maps:
        output: true
    videos:
        output: true
        permalink: /:collection/:title

navlinks:
  - text: Maps
    url: '#'
    subnav:
    - text: Akron Area
      url: /akron-area-fishing-map/
    - text: Cleveland Area
      url: /cleveland-fishing-map/
    - text: Lake Erie
      url: /lake-erie-fishing-map/
    - text: AEP
      url: /aep-fishing-map/
  - text: Videos
    url: /videos/
  - text: Bio
    url: /authors/dan-schaefer/
  - text: Shop
    url: https://afishingaddiction.square.site/
    target: _blank
    className: highlight

include: ['_pages']

defaults:
  - scope:
      path: pinterest-ecd6b.html
    values:
      sitemap: false


# The release of Jekyll Now that you're using
version: v3.9.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

jekyll-press:
  exclude: ''
  js_options: {}
  css_options: {}
  html_options: {}

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from
  - jekyll-press # Minifies all html, js, and css

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - docker-compose.yml
