jekyll:
    image: jekyll/jekyll:pages
    command: rm -rf ./_site/*
    command: jekyll serve --watch --incremental --drafts --unpublished --future --verbose
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
