version: "3.9"
services:
  afa:
    build: .
    ports:
      - 4001:4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/srv/jekyll
