jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --force_polling --incremental --drafts --unpublished --future --verbose --trace --strict_front_matter --livereload -d /tmp/_site
    ports:
        - 4001:4000
    volumes:
        - .:/srv/jekyll
